import { type Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App 123",
  description: "Generated by create next app",
  openGraph: {
    url: "https://viniciusanchieta.dev"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}